services:
  - type: web
    name: staging-graphql-learningnetwork
    plan: free
    env: docker
    region: virginia
    autoDeploy: false
    healthCheckPath: /healthz
    envVars:
      - key: HASURA_GRAPHQL_DATABASE_URL
        fromDatabase:
          name: staging-db-learningnetwork
          property: connectionString
      - key: HASURA_GRAPHQL_ENABLE_CONSOLE
        value: true
      - key: HASURA_GRAPHQL_ADMIN_SECRET
        generateValue: true
      - key: HASURA_GRAPHQL_EXPERIMENTAL_FEATURES
        value: naming_convention
      - key: HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION
        value: graphql-default
      - key: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
        value: anonymous
      - key: HASURA_FF_NAMING_CONVENTION_SEP_2023
        value: true
databases:
  - name: staging-db-learningnetwork
    postgresMajorVersion: 18
    plan: free
    region: virginia
